### ISSUE TITLE
Is this totally abandoned?

### ISSUE THREAD

**Issue by liamzee** [aiya000/hs-zuramaru#1]
I'm learning Common Lisp right now, and might be interested in forking it.

**Comment by aiya000** [comment]
Hi! Thank you for having an interest in!

Unfortunately, this project is abandoned.
But this may help you to learn of implementing a Lisp dialect.
Specs of Readme is satisfied :D

**Comment by aiya000** [comment]
Or if you want tm learn just Common Lisp (not a dialect), I think you shoud see another one.
This project is an dialect :)

**Comment by liamzee** [comment]
[ありがとうございます].

**Comment by aiya000** [comment]
こちらこそ！
